dist: trusty
sudo: required
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake
      - libgtest-dev
script:
  # Link gcc-6 and g++-6 to their standard commands
  - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
  # Export CC and CXX to tell cmake which compiler to use
  - export CC=/usr/bin/gcc-6
  - export CXX=/usr/bin/g++-6
  # Check versions of gcc, g++ and cmake
  - gcc-6 -v && g++-6 -v && cmake --version
  
jobs:
  include:
    - stage: Build
      script: 
        - g++-6 -std=c++14 Part1/part1.cpp
        - g++-6 -std=c++14 Part2/part2.cpp 
        - g++-6 -std=c++14 Part4/part4.cpp 
        - g++-6 -std=c++14 part5/part5.cpp 
        - g++-6 -std=c++14 preproc/preproc1.cpp
        - g++-6 -std=c++14 preproc2/preproc2.cpp
    - stage: Test
      script: g++-6 -std=c++14 Sample-Test1/test.cpp
  # Run your build commands next
