dist: trusty
sudo: required
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake
  
jobs:
  include:
    - stage: Build
      script: 
        - g++-6 -pthread -std=c++14 Part1/part1.cpp
        - g++-6 -pthread -std=c++14 Part2/part2.cpp 
        - g++-6 -pthread -std=c++14 Part4/part4.cpp 
        - g++-6 -pthread -std=c++14 part5/part5.cpp 
        - g++-6 -pthread -std=c++14 preproc/preproc1.cpp
        - g++-6 -pthread -std=c++14 preproc2/preproc2.cpp
        - g++-6 -pthread -o unit.out -std=c++14 Sample-Test1/unitTest.cpp
        - g++-6 -pthread -o integration.out -std=c++14 Sample-Test1/integrationTest.cpp
        - g++-6 -pthread -o fonctionnel.out -std=c++14 Sample-Test1/fonctionnelTest.cpp
    - stage: Test
      script: ./unit.out
    - # stage name not required, will continue to use `test`
      script: ./integration.out
      script: ./fonctionnel.out
