dist: trusty
sudo: required
language:
  - cpp
compiler:
  - gcc-6
before_install:
  - sudo apt-get -yq --no-install-suggests --no-install-recommends --force-yes --no-upgrade install gcc-6 g++-6 cmake cppcheck clang
  
jobs:
  include:
    - stage: Analyze
      script:
        - cppcheck Part1/part1.cpp
        - cppcheck Part2/part2.cpp
        - cppcheck Part4/part4.cpp
        - cppcheck part5/part5.cpp
        - cppcheck preproc/preproc1.cpp
        - cppcheck preproc2/preproc2.cpp
        - clang --analyze -std=c++14 Part1/part1.cpp
        - clang --analyze -std=c++14 Part2/part2.cpp
        - clang --analyze -std=c++14 Part4/part4.cpp
        - clang --analyze -std=c++14 part5/part5.cpp
        - clang --analyze -std=c++14 preproc/preproc1.cpp
        - clang --analyze -std=c++14 preproc2/preproc2.cpp
    - stage: Build
      script: 
        - g++-6 -pthread -std=c++14 Part1/part1.cpp
        - g++-6 -pthread -std=c++14 Part2/part2.cpp 
        - g++-6 -pthread -std=c++14 Part4/part4.cpp 
        - g++-6 -pthread -std=c++14 part5/part5.cpp 
        - g++-6 -pthread -std=c++14 preproc/preproc1.cpp
        - g++-6 -pthread -std=c++14 preproc2/preproc2.cpp
    - stage: Test
      script:
        - ls
        - g++-6 -pthread -o unit.out -std=c++14 Sample-Test1/unitTest.cpp
        - ./unit.out
    -
      script:
        - g++-6 -pthread -o integration.out -std=c++14 Sample-Test1/integrationTest.cpp
        - ./integration.out
    -
      script:
        - g++-6 -pthread -o fonctionnel.out -std=c++14 Sample-Test1/fonctionnelTest.cpp
        - ./fonctionnel.out
