dist: trusty
sudo: required
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - cmake
      - libgtest-dev
script:
  # Link gcc-6 and g++-6 to their standard commands
  - sudo ln -s /usr/bin/gcc-5 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-5 /usr/local/bin/g++
  # Export CC and CXX to tell cmake which compiler to use
  - export CC=/usr/bin/gcc-5
  - export CXX=/usr/bin/g++-5
  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v && cmake --version
  
jobs:
  include:
    - stage: Build
      script: gcc -std=c++17 -o build Part1/part1.cpp Part2/part2.cpp Part4/part4.cpp part5/part5.cpp preproc/preproc1.cpp preproc2/preproc2.cpp
    - stage: Test
      script: gcc -std=c++11 -o test Sample-Test1/test.cpp Sample-Test1/pch.cpp
  
  # Run your build commands next
